Repository Arch666Angel/mods, pull requests merged in 2020-10, with the labels that each got.

#372 Fixed typos and inconsistencies in many locale strings
  angelsaddons-cab/changelog.txt
  angelsaddons-cab/info.json
  angelsaddons-cab/locale/en/cab.cfg
  angelsaddons-mobility/changelog.txt
  angelsaddons-mobility/info.json
  angelsaddons-mobility/locale/en/crawlertrain.cfg
  angelsaddons-mobility/locale/en/petrotrain.cfg
  angelsaddons-mobility/locale/en/smeltingtrain.cfg
  angelsaddons-storage/changelog.txt
  angelsaddons-storage/locale/en/storage.cfg
  angelsbioprocessing/changelog.txt
  angelsbioprocessing/locale/en/bio-processing.cfg
  angelsexploration/changelog.txt
  angelsexploration/locale/en/exploration.cfg
  angelsindustries/changelog.txt
  angelsindustries/info.json
  angelsindustries/locale/en/logistic.cfg
  angelsindustries/locale/en/nuclear-power.cfg
  angelsinfiniteores/changelog.txt
  angelsinfiniteores/info.json
  angelsinfiniteores/locale/en/names.cfg
  angelspetrochem/changelog.txt
  angelspetrochem/info.json
  angelspetrochem/locale/en/petrochem.cfg
  angelsrefining/changelog.txt
  angelsrefining/info.json
  angelsrefining/locale/en/ore-refining.cfg
  angelsrefining/locale/en/water-treatment.cfg
Labels: Impact: Enhancement

#406 Fixed some bobclasses are not startable in some configurations (#394)
  angelsrefining/changelog.txt
  angelsrefining/control.lua
Labels: hacktoberfest-accepted

#408 Components total raw (#352)
  angelsindustries/changelog.txt
  angelsindustries/prototypes/recipes/components-batteries-recipes.lua
  angelsindustries/prototypes/recipes/components-blocks-recipes.lua
  angelsindustries/prototypes/recipes/components-cabling-recipes.lua
  angelsindustries/prototypes/recipes/components-construction-recipes.lua
  angelsindustries/prototypes/recipes/components-electronics-recipes.lua
  angelsindustries/prototypes/recipes/components-mechanical-recipes.lua
  angelsindustries/prototypes/recipes/components-weapons-recipes.lua
Labels: hacktoberfest-accepted

#405 Fast replace modifications
  angelsindustries/prototypes/overrides/global-tech-base-packs.lua
  angelsrefining/prototypes/angels-functions.lua
  angelsrefining/prototypes/override-functions.lua
Labels: Angels Industries, Angels Lib, Impact: Mod compatibility
